### PR TITLE
fix bug: allow optional filed maxunavilable to be nil in ads, and set default …

### LINKED ISSUE #1006: [BUG] Why Optional Field <MaxUnavailable> can not be set nil?
**What happened**:
I use advanced daemonset and update with partition feature. However, when I update to v1.1.0, I can not update when I don't set MaxUnavailable and MaxSurge with kruise controller log error msg "couldn't get unavailable numbers: invalid value for MaxUnavailable: nil value for IntOrString".

**What you expected to happen**:

As api doc said: "// The maximum number of DaemonSet pods that can be unavailable during the
	// update. Value can be an absolute number (ex: 5) or a percentage of total
	// number of DaemonSet pods at the start of the update (ex: 10%). Absolute
	// number is calculated from percentage by rounding up.
	// This cannot be 0 if MaxSurge is 0
	// Default value is 1.
	// Example: when this is set to 30%, at most 30% of the total number of nodes
	// that should be running the daemon pod (i.e. status.desiredNumberScheduled)
	// can have their pods stopped for an update at any given time. The update
	// starts by stopping at most 30% of those DaemonSet pods and then brings
	// up new DaemonSet pods in their place. Once the new pods are available,
	// it then proceeds onto other DaemonSet pods, thus ensuring that at least
	// 70% of original number of DaemonSet pods are available at all times during
	// the update.
	// +optional".
This is an optional field and default value is 1.

**How to reproduce it (as minimally and precisely as possible)**:
update daemon with nil MaxUnavailable.

**Anything else we need to know?**:

**Environment**:
- Kruise version: v1.1.0
- Kubernetes version (use `kubectl version`): 1.16
- Install details (e.g. helm install args): 
- Others:

### PR DESCRIPTION
**Pull request by ABNER-1**
fix bug: allow optional filed max unavilable in ads, and set default value 1

### Ⅰ. Describe what this PR does

1. allow optional filed max unavilable to be nil in ads
2. set max unavilable default value to 1

### Ⅱ. Does this pull request fix one issue?

fixes #1006

### Ⅲ. Describe how to verify it
update ads with nil MaxUnavailable.

### CODE REVIEW

File: pkg/controller/daemonset/daemonset_util.go [hunk 1]
```diff
@@ -254,7 +254,10 @@ func unavailableCount(ds *appsv1alpha1.DaemonSet, numberToSchedule int) (int, er
 	}
 	r := ds.Spec.UpdateStrategy.RollingUpdate
 	if r == nil {
-		return 0, nil
+		return 1, nil
```
Comment (FillZpp) [inline pkg/controller/daemonset/daemonset_util.go:257]: This should not be changed.

File: pkg/controller/daemonset/daemonset_util.go [hunk 2]
```diff
@@ -254,7 +254,10 @@ func unavailableCount(ds *appsv1alpha1.DaemonSet, numberToSchedule int) (int, er
...
+	}
+	if r.MaxUnavailable == nil {
+		return 1, nil
```
Comment (FillZpp) [inline pkg/controller/daemonset/daemonset_util.go:260]: It should return `0` which is same as maxSurge ([here](https://github.com/openkruise/kruise/blob/master/pkg/controller/daemonset/daemonset_util.go#L266)), and then controller will set `maxUnavailable` to `1` if they are all `0` ([here](https://github.com/openkruise/kruise/blob/master/pkg/controller/daemonset/daemonset_update.go#L258)).

File: pkg/controller/daemonset/daemonset_util.go (hunk 1 above)
Comment (ABNER-1) [reply pkg/controller/daemonset/daemonset_util.go:257]: I just refer to the implementation of max surge and return the default value of maxunavilable in the doc.
Sorry to change this because I did not read all codes in ds reconcile function.

Comment (ABNER-1) [reply pkg/controller/daemonset/daemonset_util.go:257]: Why I can not set default value when rollingupdate is nil?
This code is necessary when the webhook is unreachabole in my case.

**Review by FillZpp — APPROVED** [review]
/lgtm

Thanks!
