### PR TITLE
fix updated pod cannot inplace update again

### LINKED ISSUE #676: [BUG] Pod with Updated state cannot update/rollback
**What happened**:
Setting cloneset with inplace update lifecycle hook, when pod enter to Updated state, make cloneset rollback the image or update to new image, the pod with Updated state will skip to update.

**What you expected to happen**:
can update Updated pod in the premise of not loss traffic

**How to reproduce it (as minimally and precisely as possible)**:
Create a cloneset with replicas 1, lifecycle hook, InPlaceIfPossible strategy. Update the cloneset image to some bad image(which will make pod not ready). When pod enter into Updated state, rollback cloneset, it will stuck.

**Anything else we need to know?**:

**Environment**:
- Kruise version: v0.9.0
- Kubernetes version (use `kubectl version`): v1.19.3
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by shiyan2016**
### Ⅰ. Describe what this PR does
fix updated pod cannot inplace update again

### Ⅱ. Does this pull request fix one issue?

fixes #676

### CODE REVIEW

File: pkg/controller/cloneset/sync/cloneset_update.go [hunk 1]
```diff
@@ -187,16 +196,19 @@ func (c *realControl) updatePod(cs *appsv1alpha1.CloneSet, coreControl clonesetc
...
 			switch state := lifecycle.GetPodLifecycleState(pod); state {
-			case "", appspub.LifecycleStateNormal:
-				var err error
-				var updated bool
-				if cs.Spec.Lifecycle != nil && lifecycle.IsPodHooked(cs.Spec.Lifecycle.InPlaceUpdate, pod) {
-					if updated, err = c.lifecycleControl.UpdatePodLifecycle(pod, appspub.LifecycleStatePreparingUpdate); err == nil && updated {
-						clonesetutils.ResourceVersionExpectations.Expect(pod)
-						klog.V(3).Infof("CloneSet %s update pod %s lifecycle to PreparingUpdate",
-							clonesetutils.GetControllerKey(cs), pod.Name)
+			case "", appspub.LifecycleStateNormal, appspub.LifecycleStateUpdated:
```
Comment (FillZpp) [inline pkg/controller/cloneset/sync/cloneset_update.go:199]: How about keep the `appspub.LifecycleStateNormal` logic, add another `appspub.LifecycleStateUpdated`:

```golang
    case "", appspub.LifecycleStateNormal:
        // ...
    case appspub.LifecycleStateUpdated:
        var inPlaceUpdateHandler *appspub.LifecycleHook
        if cs.Spec.Lifecycle != nil {
            inPlaceUpdateHandler = cs.Spec.Lifecycle. InPlaceUpdate
        }
	if updated, err = c.lifecycleControl.UpdatePodLifecycleWithHandler(pod, appspub.LifecycleStatePreparingUpdate, inPlaceUpdateHandler); err == nil && updated {
		// ...
	}
	return 0, err
```

The `UpdatePodLifecycleWithHandler` function should patch pod with not only the lifecycle state, but also the finalizers and labels in the given handler.

This will also solve the problem in this PR that the pod object is changed in `SetPodLifecycleHook` but nowhere to update it to apiserver.

File: pkg/controller/cloneset/sync/cloneset_update.go [hunk 2]
```diff
@@ -86,9 +86,18 @@ func (c *realControl) Update(cs *appsv1alpha1.CloneSet,
 		}
 		if waitUpdate {
 			switch lifecycle.GetPodLifecycleState(pod) {
-			case appspub.LifecycleStatePreparingDelete, appspub.LifecycleStateUpdated:
+			case appspub.LifecycleStatePreparingDelete:
 				klog.V(3).Infof("CloneSet %s/%s find pod %s in state %s, so skip to update it",
 					cs.Namespace, cs.Name, pod.Name, lifecycle.GetPodLifecycleState(pod))
+			case appspub.LifecycleStateUpdated:
+				if clonesetutils.EqualToRevisionHash("", pod, updateRevision.Name) {
```
[the remark this answers is not in the document]
Comment (shiyan2016) [reply pkg/controller/cloneset/sync/cloneset_update.go]: done

File: pkg/controller/cloneset/sync/cloneset_update.go (hunk 1 above)
Comment (shiyan2016) [reply pkg/controller/cloneset/sync/cloneset_update.go]: done

File: pkg/util/lifecycle/lifecycle_utils.go [hunk 3]
```diff
@@ -96,6 +98,52 @@ func (c *realControl) UpdatePodLifecycle(pod *v1.Pod, state appspub.LifecycleSta
 	return true, err
 }
 
+func (c *realControl) UpdatePodLifecycleWithHandler(pod *v1.Pod, state appspub.LifecycleStateType, inPlaceUpdateHandler *appspub.LifecycleHook) (bool, error) {
+	if inPlaceUpdateHandler == nil || pod == nil {
```
Comment (FillZpp) [inline pkg/util/lifecycle/lifecycle_utils.go:102]: if `inPlaceUpdateHandler` is nil, maybe we should turn to the `UpdatePodLifecycle` instead of directly return?
