### PR TITLE
fix #844 When updating statefullset, the total number of pods being u…

### LINKED ISSUE #844: [BUG] When updating statefullset, the total number of pods being updated may exceed the expected value
**What happened**:
commit  id `02685e224be0215f48d8bb7b23d7892bbfaa9c5f` remove [`updateExpectations.ExpectUpdated`](https://github.com/openkruise/kruise/commit/02685e224be0215f48d8bb7b23d7892bbfaa9c5f#diff-a1e25eb50e4b2aed8947c2caa5d6d1ddfef1a5f2f95fdf71f2388c657823ee13L706) in statefulset .  
This will make `updateExpectations` not working, and may cause the `reconcile function` to obtain an informer cache that has not been updated.

**What you expected to happen**:
`updateExpectations`should not be satisfied when the informer cache has not been updated.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
When informer cahce is not updated in time and the user changes the update order, it may cause the number of updated pods to exceed the expected value(maxUnavailable or partition)

**Environment**:
- Kruise version: 0.10.0
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by hzyfox**
### Ⅰ. Describe what this PR does
Add `updateExpectations.ExpectUpdated` back to `StatefulSet`

### Ⅱ. Does this pull request fix one issue?
fix #844

### CODE REVIEW

File: pkg/controller/statefulset/stateful_set_control.go [hunk 1]
```diff
@@ -861,7 +861,7 @@ func (ssc *defaultStatefulSetControl) inPlaceUpdatePod(
 				ssc.recorder.Eventf(set, v1.EventTypeNormal, "SuccessfulUpdatePodInPlace", "successfully update pod %s in-place(revision %v)", pod.Name, updateRevision.Name)
 				return res.InPlaceUpdate, nil
 			}
-
+			updateExpectations.ExpectUpdated(getStatefulSetKey(set), updateRevision.Name, pod)
```
Comment (FillZpp) [inline pkg/controller/statefulset/stateful_set_control.go:864]: Should it be in the `if res.UpdateErr == nil { ... }` above?

Comment (hzyfox) [reply pkg/controller/statefulset/stateful_set_control.go]: Done.  Maybe we should add some unit tests to cover this scenario

**Review by FillZpp — APPROVED** [review]
/lgtm
