### PR TITLE
SidecarSet hot upgrade containers should be consistent with pod's

### LINKED ISSUE #855: [BUG] SidecarSet container upgrade type may be inconsistent with the context of pods, which will lead to panic.
**What happened**:
1. At first, I applied a sidecarset with cold-upgrade type.
```shell
$ k get sidecarset test-sidecarset -oyaml | grep -i "upgradeType:"
      upgradeType: ColdUpgrade
```
2. Later, I changed my mind, and want to modify this sidecarset as hot-upgrade style. But, I found the sidecarset webhook reject my mutation request.
```shell
error: sidecarsets.apps.kruise.io "test-sidecarset" could not be patched: admission webhook "vsidecarset.kb.io" denied the request: spec.containers.upgradeStrategy.upgradeType: Invalid value: "sidecar-2": container sidecar-2 upgradeType is immutable
```

3.  Hence,  I decided to delete this sidecarset firstly, and then to apply a new sidecarset with hot-upgrade type. 
``` shell
$ k delete sidecarset test-sidecarset
sidecarset.apps.kruise.io "test-sidecarset" deleted

$ k apply -f ../sample/sidecarset.yaml
sidecarset.apps.kruise.io/test-sidecarset created

$ k get sidecarset test-sidecarset -oyaml | grep -i "upgradeType:"
      upgradeType: HotUpgrade
```

4. Unfortunately, the new hot-upgrade sidecarsets may select the old pods that were injected by old cold-sidecarset, and will regard them as hot-upgrade pod, which will cause panic when update the sidecarset due to different configurations between cold and hot upgrade type.
```shell
$ k edit sidecarset test-sidecarset
error: sidecarsets.apps.kruise.io "test-sidecarset" could not be patched: Internal error occurred: failed calling webhook "msidecarset.kb.io": failed to call webhook: Post "https://kruise-webhook-service.kruise-system.svc:443/mutate-apps-kruise-io-v1alpha1-sidecarset?timeout=10s": dial tcp 10.96.187.179:443: connect: connection refused

$ kk get pod
NAME                                         READY   STATUS             RESTARTS       AGE
kruise-controller-manager-769f4f99bf-gg87p   0/1     CrashLoopBackOff   13 (52s ago)   20h
```

**What you expected to happen**:
A sidecarset should only care about the pods which are consistent with it.

**How to reproduce it (as minimally and precisely as possible)**:
plz see "**What happened**"

### PR DESCRIPTION
**Pull request by veophi**
Signed-off-by: veophi <vec.g.sun@gmail.com>

### Ⅰ. Describe what this PR does

SidecarSet hot upgrade containers should be consistent with pod's, otherwise, will not match the pod/sidecarset.

Ⅱ. Does this pull request fix one issue?
fixed #855

### CODE REVIEW

File: pkg/webhook/pod/mutating/sidecarset.go [hunk 1]
```diff
@@ -79,6 +79,10 @@ func (h *PodCreateHandler) sidecarsetMutatingPod(ctx context.Context, req admiss
 		} else if !matched {
 			continue
 		}
+		// if it is update event, check whether pod is consistent with sidecarSet container upgrade type
+		if isUpdated && !sidecarcontrol.IsPodConsistentWithSidecarSetContainerUpgradeType(pod, &sidecarSet) {
```
Comment (zmberg) [inline pkg/webhook/pod/mutating/sidecarset.go:83]: if isPodInjectedSidecar(s, pod) && !sidecarcontrol.IsPodConsistentWithSidecarSetContainerUpgradeType(pod, &sidecarSet) {
   continue
}

Comment (veophi) [reply pkg/webhook/pod/mutating/sidecarset.go]: done

File: pkg/control/sidecarcontrol/util.go [hunk 2]
```diff
@@ -213,6 +213,32 @@ func GetPodsSortFunc(pods []*corev1.Pod, waitUpdateIndexes []int) func(i, j int)
...
+	return sidecarSetNames.Has(sidecarSet.Name)
+}
+
+func IsPodConsistentWithSidecarSet(pod *corev1.Pod, sidecarSet *appsv1alpha1.SidecarSet) bool {
+	for i := range sidecarSet.Spec.Containers {
+		sc := &sidecarSet.Spec.Containers[i]
+		var container *corev1.Container
+		switch sc.UpgradeStrategy.UpgradeType {
+		case appsv1alpha1.SidecarContainerHotUpgrade:
+			container = util.GetContainer(fmt.Sprintf("%v-1", sc.Name), pod)
```
Comment (furykerry) [inline pkg/control/sidecarcontrol/util.go:231]: also check for the backup container?
			container2 = util.GetContainer(fmt.Sprintf("%v-2", sc.Name), pod)

Comment (veophi) [reply pkg/control/sidecarcontrol/util.go]: done

**Review by furykerry — COMMENTED** [review]
/lgtm

**Review by FillZpp — APPROVED** [review]
/lgtm
