### PR TITLE
expose defaultTTlSecondsForAlways for nodeimage

### LINKED ISSUE #2213: [BUG] setting ttlSecondsAfterFinished in AdvancedCronJob will cause the job run again and again
**What happened**:
when specify the completionPolicy.ttlSecondsAfterFinished in AdvancedCronJob, the broadcastjob will auto be deleted after timeout, but then it will be scheduled again and again

**What you expected to happen**:
job should not be started again

**How to reproduce it (as minimally and precisely as possible)**:
1. create AdvancedCronJob which should run at a fix time
```
apiVersion: apps.kruise.io/v1beta1
kind: AdvancedCronJob
metadata:
    name: acj-job
    namespace: default
spec:
    concurrencyPolicy: Replace
    failedJobsHistoryLimit: 5
    paused: false
    timeZone: Asia/Shanghai
    schedule: "46 21 * * *"
    successfulJobsHistoryLimit: 3
    template:
      broadcastJobTemplate:
        spec:
         template:
          spec:
           containers:
           - name: test
             image: alpine
             command: ["sleep", "10"]
           restartPolicy: Never
         completionPolicy:
          type: Always
          ttlSecondsAfterFinished: 30

```
2. watch kubectl get broadcastjob
3. the job will deleted after 40 seconds, then it will ber started again

**Anything else we need to know?**:
1. actually when I manually delete the broadcastjob, it also restart
2. the root cause is watchBroadcastJob() method is watching all broadcasejob resource change event, include delete, and will recreate it in the reconcileBroadcastJob() as a missing job
3. this issue also impact the newly added feature #2207

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

### LINKED ISSUE #2214: [BUG] expose the default ttlSecondsAfterFinished as a parameter for kruise-controller-manager
**What happened**:
Currently when set completionPolicy.ttlSecondsAfterFinished in ImagePullListJob, both job and tags in nodeimage are deleted when timeout.
However with feature #2207 introduced, we can schedule job with AdvancedCronJob now, the ImagePullListJob history should be maintained by successfulJobsHistoryLimit and failedJobsHistoryLimit.
So if user also set the ttlSecondsAfterFinished, the job would also be deleted.

**What you expected to happen**:
User should not set completionPolicy.ttlSecondsAfterFinished, but still have ability to control the ttl for nodeimage data, as it would be too large if not clean up.

**How to reproduce it (as minimally and precisely as possible)**:
1. create AdvancedCronJob with imageListPullJobTemplate
```
kind: AdvancedCronJob
metadata:
    name: acj-test
    namespace: default
spec:
    concurrencyPolicy: Replace
    paused: false
    schedule: "*/2 * * * *"
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 5
    template:
      imageListPullJobTemplate:
        spec:
          completionPolicy:
            ttlSecondsAfterFinished: 30
            type: Always
          imagePullPolicy: IfNotPresent
          images:
          - busybox
          parallelism: 2
          pullPolicy:
            backoffLimit: 1
            timeoutSeconds: 10
    timeZone: Asia/Shanghai
```
2. only data in nodeimage should be deleted after 30 seconds

**Anything else we need to know?**:

**Environment**:
- Kruise version: master branch
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

### PR DESCRIPTION
**Pull request by bitsf**
### Ⅰ. Describe what this PR does
expose defaultTTlSecondsForAlways as a environment for nodeimage, that can allow user to controller the default ttl for nodeimage status, in case user don't want to use the same ttl for imagepulljob

### Ⅱ. Does this pull request fix one issue?

fix #2214
fix #2213

### Ⅲ. Describe how to verify it
1. kubectl edit deploy kruise-controller-manager, add parameter `--default-ttlseconds-for-always-nodeimage` for container manager
2. create imagepulljob
3. check the nodeimage ttlSecondsAfterFinished value
4. for detailed calculation methods, please refer to the test case

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -128,6 +130,7 @@ func main() {
 		"leader-election-retry-period is the duration the LeaderElector clients should wait between tries of actions. Default is 2 seconds.")
 	flag.DurationVar(&controllerCacheSyncTimeout, "controller-cache-sync-timeout", defaultControllerCacheSyncTimeout, "CacheSyncTimeout refers to the time limit set to wait for syncing caches. Defaults to 2 minutes if not set.")
 	flag.DurationVar(&webhookInitializeTimeout, "webhook-initialize-timeout", defaultWebhookInitializeTimeout, "WebhookInitializeTimeout refers to the time limit set to wait for webhook initialization. Defaults to 60 seconds if not set.")
+	flag.IntVar(&defaultTtlForAlwaysNodeimage, "default-ttl-for-always-nodeimage", defaultTtlForAlwaysNodeimageConst, "DefaultTtlForAlwaysNodeimage refers to the calculation of the time limit the lifetime of a pulling task that has finished execution. Defaults to 300 seconds if not set.")
```
Comment (furykerry) [inline main.go]: if value is not time.Duration, then we should be more explicit that what unit default-ttl-for-always-nodeimage use. Consider rename it to default-ttlseconds-for-always-nodeimage
