### PR TITLE
daemon reports runtime-container-meta to support in-place update with same imageID

### LINKED ISSUE #635: [BUG] inplace update process will be hang up when the image id is not changed
**What happened**:

First, create a cloneset `sample` by using the following yaml content:
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - image: nginx:1.18
        name: nginx
  updateStrategy:
    partition: 3  --- !!! equal to the replicas !!!
    type: InPlaceOnly
```
apply it, watch the pods by command `kubectl get pod  -L controller-revision-hash -L lifecycle.apps.kruise.io/state -w`, it will work well.

Then, we edit the cloneset `sample`, modify the following fields:
```
spec:
  replicas: 3
  ...
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - image: nginx-copy:1.18   --- !!! change it to a new image tag, but with the same image id with the old !!!
        ...
  updateStrategy:
    ...
    partition: 1 --- !!! change it from 3 to 1 !!!
    ...
```
Watch pods, we will see the problem: 
1. **Only one pod's revision will changed, while two pods' revision changed is expected by the meaning of the `updateStrategy.partition`, and the  update process will hung up.**
```
# Outputs below are the results after 5 minutes

% kubectl get pod  -L controller-revision-hash -L lifecycle.apps.kruise.io/state -w
NAME           READY   STATUS    RESTARTS   AGE   CONTROLLER-REVISION-HASH   STATE
sample-7jrpp   1/1     Running   1          5m   sample-648847746c          Updating   --- !!! continues to be Updating !!!
sample-cgsr6   1/1     Running   0          5m   sample-7f4d7465f8          Normal
sample-vzbpx   1/1     Running   0          5m   sample-7f4d7465f8          Normal
```

2. The label `lifecycle.apps.kruise.io/state`'s value continues to be `Updating` for the pod which revision changed.
3. The status of cloneset `sample` is:
```
status:
  availableReplicas: 2
  collisionCount: 0
  currentRevision: sample-7f4d7465f8
  labelSelector: app=sample
  observedGeneration: 2
  readyReplicas: 2
  replicas: 3
  updateRevision: sample-648847746c
  updatedReadyReplicas: 0  --- !!! continues to be 0 !!!
  updatedReplicas: 1   --- !!! continues to be 1 !!!
```

**What you expected to happen**:

Two pods' revision changed, and the status of cloneset and pods should be normal.

**How to reproduce it (as minimally and precisely as possible)**:

See the description above.

**Anything else we need to know?**:

I tried to fix this problem at https://github.com/openkruise/kruise/pull/636

**Environment**:
- Kruise version: v0.9.0 / master branch
- Kubernetes version (use `kubectl version`): v1.20.2 (installed by kind on MAC)
- OS (e.g: `cat /etc/os-release`): MAC OS
- Kernel (e.g. `uname -a`):
- Install tools: helm
- Others:

### PR DESCRIPTION
**Pull request by FillZpp**
Signed-off-by: FillZpp <FillZpp.pub@gmail.com>

### Ⅰ. Describe what this PR does
Kruise-daemon reports runtime-container-meta to support in-place update with same imageID.

### Ⅱ. Does this pull request fix one issue?

fixes #635 
related #644

### CODE REVIEW

File: pkg/daemon/containermeta/container_meta_controller.go [hunk 1]
```diff
@@ -0,0 +1,289 @@
...
+
+// NewController returns the Controller for containermeta reporting
+func NewController(opts daemonoptions.Options) (*Controller, error) {
+	if opts.PodInformer == nil {
+		return nil, fmt.Errorf("containermeta Controller can not run without pod informer")
+	}
+
+	queue := workqueue.NewNamedRateLimitingQueue(
+		// Backoff duration from 500ms to 50~55s
+		workqueue.NewItemExponentialFailureRateLimiter(500*time.Millisecond, 50*time.Second+time.Millisecond*time.Duration(rand.Intn(5000))),
```
[the remark this answers is not in the document]
Comment (FillZpp) [reply pkg/daemon/containermeta/container_meta_controller.go:70]: ignore

File: pkg/util/inplaceupdate/inplace_update_defaults.go [hunk 2]
```diff
@@ -149,18 +141,27 @@ func defaultCalculateInPlaceUpdateSpec(oldRevision, newRevision *apps.Controller
...
-	//}
+	runtimeContainerMetaSet, err := appspub.GetRuntimeContainerMetaSet(pod)
+	if err != nil {
+		return err
+	}
+	if runtimeContainerMetaSet != nil {
+		if checkAllContainersHashConsistent(pod, runtimeContainerMetaSet) {
+			klog.V(5).Infof("Check Pod %s/%s in-place update completed for all container hash consistent", pod.Namespace, pod.Name)
+			return nil
+		}
```
Comment (zmberg) [inline pkg/util/inplaceupdate/inplace_update_defaults.go:163]: Shouldn't we just return error here?

File: pkg/util/inplaceupdate/inplace_update_defaults.go [hunk 3]
```diff
@@ -149,18 +141,27 @@ func defaultCalculateInPlaceUpdateSpec(oldRevision, newRevision *apps.Controller
 // If the imageID in containerStatuses has not been changed, we assume that kubelet has not updated
 // containers in Pod.
 func DefaultCheckInPlaceUpdateCompleted(pod *v1.Pod) error {
+	if _, isInGraceState := appspub.GetInPlaceUpdateGrace(pod); isInGraceState {
+		return fmt.Errorf("still in grace period of in-place update")
+	}
+
 	inPlaceUpdateState := appspub.InPlaceUpdateState{}
```
Comment (zmberg) [inline pkg/util/inplaceupdate/inplace_update_defaults.go:148]: Is this here for compatibility with the old logic, when runtimeContainerMetaSet!=nil, there should be no need to parse anymore?

File: pkg/daemon/containermeta/container_meta_controller.go [hunk 4]
```diff
@@ -0,0 +1,290 @@
...
+	containerMetaSet := c.generateContainerMetaSet(pod, kubePodStatus)
+	oldContainerMetaSet, err := appspub.GetRuntimeContainerMetaSet(pod)
+	if err != nil {
+		klog.Warningf("Failed to get old runtime meta from Pod %s/%s: %v", namespace, name, err)
+		oldContainerMetaSet = nil
+	}
+	if reflect.DeepEqual(containerMetaSet, oldContainerMetaSet) {
+		return nil
+	}
+
```
Comment (zmberg) [inline pkg/daemon/containermeta/container_meta_controller.go:232]:
```
        oldContainerMetaSet, err := appspub.GetRuntimeContainerMetaSet(pod)
	if err != nil {
		klog.Warningf("Failed to get old runtime meta from Pod %s/%s: %v", namespace, name, err)
	}else if reflect.DeepEqual(containerMetaSet, oldContainerMetaSet) {
		return nil
	}
```

File: pkg/util/inplaceupdate/inplace_update_defaults.go (hunk 2 above)
Comment (FillZpp) [reply pkg/util/inplaceupdate/inplace_update_defaults.go:163]: Sometimes users might not have kruise-daemon on each node, e.g. some nodes are created by VK. So we can't totally rely on the annotation report.

Comment (FillZpp) [reply pkg/util/inplaceupdate/inplace_update_defaults.go:163]: If the kruise-daemon used to report meta annotation and now it has broken for some reason, we expect it as no effect on pods update as possible.

File: pkg/util/inplaceupdate/inplace_update_defaults.go (hunk 3 above)
Comment (FillZpp) [reply pkg/util/inplaceupdate/inplace_update_defaults.go]: Have moved this behind runtimeContainerMetaSet. So that if we check container hashes are consistent, it will not unmarshal inPlaceUpdateState.

File: pkg/daemon/containermeta/container_meta_controller.go (hunk 4 above)
Comment (FillZpp) [reply pkg/daemon/containermeta/container_meta_controller.go:231]: updated

File: pkg/daemon/containermeta/container_meta_controller.go [hunk 5]
```diff
@@ -0,0 +1,309 @@
...
+			ownedByKruise = gv.Group == appsv1alpha1.GroupVersion.Group
+		}
+	}
+	_, injectedBySidecarSet := pod.Annotations[sidecarcontrol.SidecarSetHashAnnotation]
+	if !ownedByKruise && !injectedBySidecarSet {
+		return false
+	}
+
+	// Is containerID changed?
+	containerMetaSet, _ := appspub.GetRuntimeContainerMetaSet(pod)
```
[the remark this answers is not in the document]
Comment (FillZpp) [reply pkg/daemon/containermeta/container_meta_controller.go:128]: It is checked when enqueue https://github.com/FillZpp/kruise/blob/daemon-report-container-hash-in-pod-annotation/pkg/daemon/containermeta/container_meta_controller.go#L148

File: pkg/daemon/containermeta/container_meta_controller.go [hunk 6]
```diff
@@ -0,0 +1,309 @@
...
+	} else if reflect.DeepEqual(containerMetaSet, oldContainerMetaSet) {
+		return nil
+	}
+
+	containerMetaSetStr := util.DumpJSON(containerMetaSet)
+	klog.Infof("Find container meta changed in Pod %s/%s, new: %v", namespace, name, containerMetaSetStr)
+	patchBody := util.DumpJSON(
+		patchContainerMeta{Metadata: patchContainerMetaData{Annotations: map[string]string{appspub.RuntimeContainerMetaKey: containerMetaSetStr}}},
+	)
+	resPod, err := c.kubeClient.CoreV1().Pods(namespace).Patch(context.TODO(), name, types.StrategicMergePatchType, []byte(patchBody), metav1.PatchOptions{})
```
[the remark this answers is not in the document]
Comment (FillZpp) [reply pkg/daemon/containermeta/container_meta_controller.go]: Have changed to status patch.

File: pkg/daemon/containermeta/container_meta_controller.go [hunk 7]
```diff
@@ -0,0 +1,306 @@
...
+
+	containerMetaSet := c.generateContainerMetaSet(pod, kubePodStatus)
+	oldContainerMetaSet, err := appspub.GetRuntimeContainerMetaSet(pod)
+	if err != nil {
+		klog.Warningf("Failed to get old runtime meta from Pod %s/%s: %v", namespace, name, err)
+	} else if reflect.DeepEqual(containerMetaSet, oldContainerMetaSet) {
+		return nil
+	}
+
+	pod = pod.DeepCopy()
```
Comment (furykerry) [inline pkg/daemon/containermeta/container_meta_controller.go:252]: there is no need to copy every bit of pod during a status update since only the meta and status is used by the apiserver. We can save the cpu time for deepcopy pod spec

**Review by furykerry — COMMENTED** [review]
/lgtm
