### PR TITLE
fix: bcj doesn't make pod on node that has erased taint

### LINKED ISSUE #1199: [BUG] node has erased its taint，but broadcastjob won't make a pod on that node
**What happened**:
k8s集群有一个节点有unschedule taint, 此时提交了一个broadcastjob, pod没有在该 node 上创建，这是符合预期的。
但是当该节点taint被消除后，broadcastjob仍然不会在该node上创建pod。

**What you expected to happen**:
broadcastjob会在节点taint被清除后在该节点上创建pod

**How to reproduce it (as minimally and precisely as possible)**:
cordon一个节点。
提交一个 broadcastjob

```
apiVersion: apps.kruise.io/v1alpha1
kind: BroadcastJob
metadata:
  name: busybox
spec:
  template:
    spec:
      containers:
        - name: main
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ["sleep", "100"]        
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
      restartPolicy: OnFailure
  completionPolicy:
    type: Never
  failurePolicy:
    type: Continue
```

然后再 uncordon 该节点，没有pod被新建出来

**Anything else we need to know?**:
我分析了代码发现: 
broadcastjob_event_handler.go line141这里 `canOldNodeFit, err := checkNodeFitness(mockPod, oldNode)`
返回err就会直接continue，而不会去检查新的node状态是否已经把taint清除了，这个是不是不妥？

```
func (p *enqueueBroadcastJobForNode) updateNode(q workqueue.RateLimitingInterface, old, cur runtime.Object) {
	oldNode := old.(*v1.Node)
	curNode := cur.(*v1.Node)
	if shouldIgnoreNodeUpdate(*oldNode, *curNode) {
		return
	}
	jobList := &v1alpha1.BroadcastJobList{}
	err := p.reader.List(context.TODO(), jobList)
	if err != nil {
		klog.Errorf("Error enqueueing broadcastjob on updateNode %v", err)
	}
	for _, bcj := range jobList.Items {
		mockPod := NewMockPod(&bcj, oldNode.Name)
		canOldNodeFit, err := checkNodeFitness(mockPod, oldNode)
		if err != nil {
			klog.Errorf("failed to checkNodeFitness for job %s/%s, on old node %s, %v", bcj.Namespace, bcj.Name, oldNode.Name, err)
			continue
		}

		canCurNodeFit, err := checkNodeFitness(mockPod, curNode)
		if err != nil {
			klog.Errorf("failed to checkNodeFitness for job %s/%s, on cur node %s, %v", bcj.Namespace, bcj.Name, curNode.Name, err)
			continue
		}

		if canOldNodeFit != canCurNodeFit {
			// enqueue the broadcast job for matching node
			q.Add(reconcile.Request{
				NamespacedName: types.NamespacedName{
					Namespace: bcj.Namespace,
					Name:      bcj.Name}})
		}
	}
}
```

**Environment**:
- Kruise version: master branch
- Kubernetes version: 1.19.16

### PR DESCRIPTION
**Pull request by weldonlwz**
### Ⅰ. Describe what this PR does
fix the bug that broadcastjob won't make pod when a tainted node has erased its taint

### Ⅱ. Does this pull request fix one issue?

fixes #1199

### Ⅲ. Describe how to verify it
1.cordon a node
2.apply a new broadcastjob, and the pod will not appear on that cordoned node
3.uncordon that node, a new pod is made 

### Ⅳ. Special notes for reviews
the returned err of function `checkNodeFitness` is not error actually, but the reason why the node is not fit

### CODE REVIEW

**Comment by weldonlwz** [comment]
@veophi it said check not success, does the commit need any update?

**Comment by veophi** [comment]
> @veophi it said check not success, does the commit need any update?

@weldonlwz we need another reviewer to approve this pr.

/cc @zmberg  
/cc @furykerry

**Comment by zmberg** [comment]
@caniszczyk very good, can you add e2e test in [e2e file](https://github.com/openkruise/kruise/blob/master/test/e2e/apps/broadcastjob.go) for this scenarios?

File: pkg/controller/broadcastjob/broadcastjob_controller.go [hunk 1]
```diff
@@ -529,11 +529,8 @@ func getNodesToRunPod(nodes *corev1.NodeList, job *appsv1alpha1.BroadcastJob,
 		// there's pod existing on the node
 		if pod, ok := existingNodeToPodMap[node.Name]; ok {
 			canFit, err = checkNodeFitness(pod, &node)
-			if err != nil {
-				klog.Errorf("pod %s failed to checkNodeFitness for node %s, %v", pod.Name, node.Name, err)
-				continue
-			}
 			if !canFit {
```
Comment (zmberg) [inline pkg/controller/broadcastjob/broadcastjob_controller.go:532]: if !canFit && pod.DeletionTimestamp == nil {
   .......
}

Comment (weldonlwz) [reply pkg/controller/broadcastjob/broadcastjob_controller.go:532]:
```
if !canFit && pod.DeletionTimestamp == nil {
	klog.Infof("Pod %s does not fit on node %s due to %v", pod.Name, node.Name, err)
	podsToDelete = append(podsToDelete, pod)
	continue
}
```

Am i correct?

Comment (zmberg) [reply pkg/controller/broadcastjob/broadcastjob_controller.go:532]: yes

Comment (weldonlwz) [reply pkg/controller/broadcastjob/broadcastjob_controller.go]: done.

**Comment by zmberg** [comment]
@weldonlwz Can you add some e2e test, so it can verify the function work.

**Comment by weldonlwz** [comment]
it occurs to me that when I taint a node with 'unschedule', we dont expect the pod on that node to be removed, right?  if then the logic to set `podsToDelete` still needs some update.

**Comment by zmberg** [comment]
> it occurs to me that when I taint a node with 'unschedule', we dont expect the pod on that node to be removed, right? if then the logic to set `podsToDelete` still needs some update.

yes, i think so. And what do you want update `PodsToDelete`?
