### PR TITLE
fix cloneset maxUnavaliable when maxSurge > 0

### LINKED ISSUE #316: [BUG] CloneSet update not expected
**What happened**:
Create a cloneset with replicas 1, and updateStrategy as follows:  
```
updateStrategy:
    maxSurge: 50%
    maxUnavailable: 10%
    partition: 0
    type: ReCreate
```
doing an update, it will delete and create new pod at the same time.

**What you expected to happen**:
After the newly pod ready，delete the old pod.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version: master
- Kubernetes version (use `kubectl version`): 1.17.4
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by shiyan2016**
### Ⅰ. Describe what this PR does
fix cloneset maxUnavaliable when maxSurge is not nil

### Ⅱ. Does this pull request fix one issue?

fixes #316

### CODE REVIEW

File: pkg/controller/cloneset/update/cloneset_update.go [hunk 1]
```diff
@@ -143,6 +143,10 @@ func calculateUpdateCount(coreControl clonesetcore.Control, strategy appsv1alpha
 
 	maxUnavailable, _ := intstrutil.GetValueFromIntOrPercent(
 		intstrutil.ValueOrDefault(strategy.MaxUnavailable, intstrutil.FromString(appsv1alpha1.DefaultCloneSetMaxUnavailable)), totalReplicas, true)
+	if strategy.MaxSurge != nil {
```
Comment (FillZpp) [inline pkg/controller/cloneset/update/cloneset_update.go:146]: How about this

```golang
roundUp := strategy.MaxSurge == nil
maxUnavailable, _ := intstrutil.GetValueFromIntOrPercent(
    intstrutil.ValueOrDefault(strategy.MaxUnavailable, intstrutil.FromString(appsv1alpha1.DefaultCloneSetMaxUnavailable)), totalReplicas, roundUp)
```

Comment (shiyan2016) [reply pkg/controller/cloneset/update/cloneset_update.go]: done, the ci check was failed by timeout, how to recheck it ?

File: pkg/controller/cloneset/update/cloneset_update.go [hunk 2]
```diff
@@ -141,8 +141,9 @@ func calculateUpdateCount(coreControl clonesetcore.Control, strategy appsv1alpha
 	}
 	waitUpdateIndexes = waitUpdateIndexes[:(len(waitUpdateIndexes) - partition)]
 
+	roundUp := strategy.MaxSurge == nil
```
Comment (FillZpp) [inline pkg/controller/cloneset/update/cloneset_update.go:144]: My fault. It is meaningless to compare with `nil`, because we have set the `maxSurge` defaults to `0` 

https://github.com/openkruise/kruise/blob/master/pkg/apis/apps/v1alpha1/defaults.go#L223

Comment (shiyan2016) [reply pkg/controller/cloneset/update/cloneset_update.go:144]: so we need to check whether maxSurge is 0, I will update it.

File: pkg/controller/cloneset/update/cloneset_update.go [hunk 3]
```diff
@@ -141,8 +141,9 @@ func calculateUpdateCount(coreControl clonesetcore.Control, strategy appsv1alpha
 	}
 	waitUpdateIndexes = waitUpdateIndexes[:(len(waitUpdateIndexes) - partition)]
 
+	roundUp := !(strategy.MaxSurge != nil && strategy.MaxSurge.IntValue() > 0)
```
Comment (FillZpp) [inline pkg/controller/cloneset/update/cloneset_update.go:144]: The question is, if `maxSurge` is percentage str, `maxSurge.IntValue()` will also return 0.

How about this:

```golang
roundUp := true
if strategy.MaxSurge != nil {
    roundUp = strategy.MaxSurge.Type == intstr.Int && strategy.MaxSurge.IntValue() == 0
}
```

Comment (shiyan2016) [reply pkg/controller/cloneset/update/cloneset_update.go:144]: But it cannot cover string type case.

Comment (shiyan2016) [reply pkg/controller/cloneset/update/cloneset_update.go:144]: how about this:
` 
roundUp := true
if strategy.MaxSurge != nil {
   maxSurge, _ := intstrutil.GetValueFromIntOrPercent(strategy.MaxSurge, totalReplicas, true)
   roundUp = maxSurge == 0
}

`

Comment (shiyan2016) [reply pkg/controller/cloneset/update/cloneset_update.go:144]: @FillZpp

Comment (FillZpp) [reply pkg/controller/cloneset/update/cloneset_update.go:144]: @shiyan2016 That's ok
